Log connect trace server uri when reconnecting
nats-io/nats.java pull request #1106
Opened 2024-03-29 18:18 UTC by photizzo

Linked [Issue](https://github.com/nats-io/nats.java/issues/547) here

2024-03-29 18:18 UTC, photizzo commented on src/test/java/io/nats/client/ConnectTests.java
> +                    .maxReconnects(1)
Limits the number of reconnect attempts for testing.

2024-03-29 18:19 UTC, photizzo commented on src/test/java/io/nats/client/ConnectTests.java
> +                ts.close();
Close the test server to trigger a reconnect attempt

2024-03-29 18:19 UTC, photizzo commented on src/test/java/io/nats/client/ConnectTests.java
> +                Thread.sleep(3000);
Waits for a reconnect attempt to occur

2024-03-29 23:29 UTC, scottf requested changes

2024-03-29 23:29 UTC, scottf commented on src/main/java/io/nats/client/impl/NatsConnection.java
> +                            timeTraceLogger.trace("reconnecting to server %s", resolved.toString());
To be consistent, this trace should be before the previous line.

2024-03-30 13:33 UTC, scottf approved these changes
LGTM

2024-03-30 13:34 UTC, merged