New connection option dontCancelNoResponders
nats-io/nats.java pull request #887
Opened 2023-04-11 21:19 UTC by scottf

With an option the exception could change from this
```
java.util.concurrent.CancellationException
```
to this
```
java.util.concurrent.ExecutionException: io.nats.client.JetStreamStatusException: (503) No Responders Available For Request
```

2023-04-11 22:59 UTC, tbeets requested changes
Suggest phrasing connection option in the positive, i.e. `reportNoResponders` rather than the negative.

2023-04-12 22:01 UTC, tbeets approved these changes
LGTM

2023-04-12 23:46 UTC, ColinSullivan1 commented on src/examples/java/io/nats/examples/DontCancelOnNoResponders.java
> +// Copyright 2020 The NATS Authors
Might want to update the copyright date while you're editing this file.

2023-04-12 23:49 UTC, ColinSullivan1 approved these changes
LGTM.

2023-04-13 00:38 UTC, merged